stages:
  - build
  - deploy


variables:
  GLOBAL_VAR: "4.0"  

criar_imagens:
  stage: build
  tags:
    - aws
  script:
  - docker build -t phaelcrypto/meusite:$GLOBAL_VAR app/.
  - docker push phaelcrypto/meusite:$GLOBAL_VAR

executar_imagens:
  stage: deploy
  needs:
    - criar_imagens
  tags:
    - aws
  before_script:
  - docker rm $(docker ps -a -q) --force
  script:
  - docker run -dti --name web-server -p 80:80 phaelcrypto/meusite:$GLOBAL_VAR   
  after_script:
  - docker system prune --force